const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTER_STARTED = "REGISTER_STARTED";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_LOADED = "USER_LOADED";
const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT = "LOGOUT";
const GET_PROFILE = "GET_PROFILE";
const PROFILE_ERROR = "PROFILE_ERROR";
const CLEAR_PROFILE = "CLEAR_PROFILE";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const ACCOUNT_DELETED = "ACCOUNT_DELETED";
const GET_ALL_PROFILES = "GET_ALL_PROFILES";
const GET_REPOS = "GET_REPOS";
const GET_POSTS = "GET_POSTS";
const POST_ERROR = "POST_ERROR";
const UPDATE_LIKES = "UPDATE_LIKES";
const DELETE_POST = "DELETE_POST";
const ADD_POST = "ADD_POST";
const GET_POST = "GET_POST";
const ADD_COMMENT = "ADD_COMMENT";
const REMOVE_COMMENT = "REMOVE_COMMENT";

export {
  SET_ALERT,
  REMOVE_ALERT,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  REGISTER_STARTED,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  GET_PROFILE,
  PROFILE_ERROR,
  CLEAR_PROFILE,
  UPDATE_PROFILE,
  ACCOUNT_DELETED,
  GET_ALL_PROFILES,
  GET_REPOS,
  GET_POSTS,
  POST_ERROR,
  UPDATE_LIKES,
  DELETE_POST,
  ADD_POST,
  GET_POST,
  ADD_COMMENT,
  REMOVE_COMMENT,
};
